# Workflow to test out what a bad user can get away with if they fork the repo.
name: Test PR Controls
on:
  push:
  workflow_dispatch: # In main, this workflow only runs manually.
  pull_request:
      types: [opened, reopened]
  pull_request_target:

jobs:
  test_export:
    runs-on: ubuntu-22.04
    steps:
    - name: Write out the branch name
      shell: bash
      run: echo github.ref_name = ${{github.ref_name}}
    - name: Use Secret
      shell: bash
      run: "echo If we echo a secret, it looks like this: ${{ secrets.FAKE_SECRET }}"
